# Generated by Django 5.0.4 on 2026-03-11 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasRider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อ')),
                ('alias', models.CharField(blank=True, max_length=100, verbose_name='ชื่อมาสไรเดอร์')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='อายุ')),
                ('series', models.CharField(choices=[('showa', 'โชวะ (Showa)'), ('heisei', 'เฮเซ (Heisei)'), ('reiwa', 'เรวะ (Reiwa)')], max_length=10, verbose_name='ยุค')),
                ('organization', models.CharField(blank=True, max_length=200, verbose_name='องค์กร')),
                ('transformation_device', models.CharField(blank=True, max_length=200, verbose_name='อุปกรณ์แปลงร่าง')),
                ('abilities', models.TextField(blank=True, verbose_name='ความสามารถ')),
                ('bio', models.TextField(blank=True, verbose_name='ประวัติ')),
                ('image_url', models.URLField(blank=True, verbose_name='URL รูปภาพ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'มาสไรเดอร์',
                'verbose_name_plural': 'มาสไรเดอร์',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompetitionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opponent', models.CharField(max_length=200, verbose_name='คู่ต่อสู้')),
                ('event_name', models.CharField(max_length=200, verbose_name='ชื่อเหตุการณ์')),
                ('event_date', models.DateField(verbose_name='วันที่')),
                ('result', models.CharField(choices=[('win', 'ชนะ'), ('lose', 'แพ้'), ('draw', 'เสมอ')], max_length=10, verbose_name='ผลการต่อสู้')),
                ('description', models.TextField(blank=True, verbose_name='รายละเอียด')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to='masrider.masrider', verbose_name='มาสไรเดอร์')),
            ],
            options={
                'verbose_name': 'ประวัติการต่อสู้',
                'verbose_name_plural': 'ประวัติการต่อสู้',
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อความสามารถ')),
                ('description', models.TextField(blank=True, verbose_name='คำอธิบาย')),
                ('power_level', models.PositiveIntegerField(default=50, verbose_name='ระดับพลัง (1-100)')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_abilities', to='masrider.masrider', verbose_name='มาสไรเดอร์')),
            ],
            options={
                'verbose_name': 'ความสามารถพิเศษ',
                'verbose_name_plural': 'ความสามารถพิเศษ',
            },
        ),
    ]
